name: pihole_manager
description: "PiHome"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  dio: ^5.5.0+1
  progress_bar_chart: ^0.0.12
  sqflite: ^2.3.3+1
  get_it: ^7.7.0
  path: ^1.9.0
  community_charts_flutter: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
